apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: cffnpwr/python-app:f8109e970f5ab9ad2ab2e8c3ebb17263e8568d6b
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /var/python-app
              name: python-app-data
      volumes:
        - name: python-app-data
          persistentVolumeClaim:
            claimName: python-app-data-pvc
