apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-app-data-pvc
spec:
  resources:
    requests:
      storage: 100M
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: share
  name: python-app-data-share-pvc
spec:
  resources:
    requests:
      storage: 100M
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
